# Generated by Django 3.1.3 on 2021-05-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserav', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['title', 'price', 'telephone']},
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.CharField(max_length=25),
        ),
    ]
