# Generated by Django 3.1.3 on 2021-05-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserav', '0002_auto_20210506_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['title']},
        ),
    ]
